name: Build wheel and create github release
on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  github-release:
    permissions:
      actions: read
      contents: write
      statuses: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Clone the source
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: install developer dependencies
      run: python -m pip install -r dev_requirements.txt
    - name: install sat-solver
      run: python -m pip install -e .
    - name: run tests
      run: python -m haas simplesat
      working-directory: ./.github
    - name: build wheel
      run: python -m build -s -w -n -x
    - name: build wheel
      run: python -m build -s -w -n -x
    - name: sign archives
      uses: sigstore/gh-action-sigstore-python@v3
      with:
        inputs: |
          dist/simplesat*.whl
          dist/simplesat*.tar.gz
        verify: true
        verify-cert-identity: https://github.com/enthought/sat-solver/.github/workflows/release.yml@refs/tags/${{github.ref_name}}
        verify-oidc-issuer: https://token.actions.githubusercontent.com
        release-signing-artifacts: true
        upload-signing-artifacts: true
    - name: Prepare release
      uses:  ./.github/actions/prepare-release
      with:
        tag: ${{ github.ref_name }}
