name: Build wheel and create github release
on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  github-release:
    permissions:
      actions: read
      contents: write
      statuses: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Clone the source
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: install developer dependencies
      run: -m pip install -r dev_requirements.txt
      shell: python
    - name: install sat-solver
      run: -m pip install -e .
      shell: python
    - name: run tests
      run: -m haas simplesat
      working-directory: ./.github
      shell: python
    - name: build wheel
      run: -m build -s -w -n -x
      shell: python
    - name: build wheel
      run: -m build -s -w -n -x
      shell: python
    - name: sign archives
      uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: dist/simplesat*.whl dist/simplesat*.tar.gz
        verify: true
        verify-cert-identity: https://github.com/enthought/sat-solver/.github/workflows/release@refs/heads/${{github.ref_name}}
        verify-oidc-issuer: https://token.actions.githubusercontent.com
    - name: Prepare release
      uses:  ./.github/actions/prepare-release
      with:
        tag: ${{ github.ref_name }}
