name: Build wheel and create github release
on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone the source
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: install developer dependencies
      run: python -m pip install -r dev_requirements.txt
    - name: install sat-solver
      run: python -m pip install -e .
    - name: run tests
      run: python -m haas simplesat
      working-directory: ./.github
  github-release:
    needs: run-tests
    permissions:
      actions: read
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
    - name: Clone the source
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: install release dependencies
      run: python -m pip install build wheel requests
    - name: build wheel
      run: python -m build -s -w -n -x
    - name: Prepare release
      uses:  ./.github/actions/prepare-release
      with:
        tag: ${{ github.ref_name }}
